spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://prod-database:5432/demo"
    username: postgres
    password: password

server:
  port: 8888

application:
  # configuring external calls
  webclient:
    read-timeout: 1000
    connect-timeout: 1000